FROM nginx:alpine

# Remove default nginx configs.
RUN rm /etc/nginx/conf.d/default.conf

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/conf.d

# Expose the port nginx is reachable on
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
