# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD 

on:
  push:
    branches: [ "main" ] 

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.0'    

    - name: Stop the existing Docker container
      run: docker stop go-cicd-container || true

    - name: Remove the existing Docker container
      run: docker rm go-cicd-container || true

    - name: Remove existing Docker image
      run: docker rmi go-cicd || true

    - name: Build the Docker image
      run: docker build . -t go-cicd

    - name: Run Docker container   
      run : docker run -d --name go-cicd-container -p 8081:8081 -v /home/actsone/local/environment/go_cicd/.env:/.env go-cicd

 
    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.22.0'

    # - name: Build
    #   run: go build -v ./...
      
